title: Jae Hoon Lee
logo: /assets/img/pic.jpg
description: I am a second-year Master's of Economics student at University of Wisconsin - Madison.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
